Home/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('webapp.urls', namespace='webapp')),
    url(r'^admin/', include(admin.site.urls)),
)

webapp/urls.py
__author__ = 'zalfonse'
from django.conf.urls import patterns, url
from views import IndexView, LoginView, PropertyView

urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^property/(?P<id>\d+)$', PropertyView.as_view(), name='property'),
    url(r'^login/.*$', LoginView.as_view(), name='login'),
    url(r'^logout/.*$', 'webapp.views.logout', name='logout')
)

webapp/models.py
from django.db import models
from urllib import quote_plus
from settings import google_api_key
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User)


class Property(models.Model):
    name = models.CharField(max_length=50)
    manager = models.ManyToManyField(User, related_name='manager')
    owner = models.ManyToManyField(User, related_name='owner')
    address = models.CharField(max_length=50)
    address2 = models.CharField(max_length=50, null=True, verbose_name='second address line')
    zip_code = models.CharField(max_length=50)
    description = models.TextField(max_length=1000, null=True)

    def __str__(self):
        return self.name + " (" + self.address + ")"

    class Meta:
        verbose_name_plural = "properties"


class Unit(models.Model):
    name = models.CharField(max_length=50)
    rent = models.DecimalField(max_digits=6, decimal_places=2)
    property = models.ForeignKey(Property)
    tenant = models.ManyToManyField(User)
    address = models.CharField(max_length=50)
    address2 = models.CharField(max_length=50, null=True)
    zip_code = models.CharField(max_length=50)
    description = models.TextField(max_length=1000, null=True)

    def get_query_location(self):
        return quote_plus(self.address + " " + self.zip_code)

    def get_street_view(self):
        url = 'http://maps.googleapis.com/maps/api/streetview?size=200x100&location={0}&fov=120&sensor=false'
        return url.format(self.get_query_location())

    def get_map(self):
        url = 'https://www.google.com/maps/embed/v1/place?key={0}&q={1}'
        print url.format(google_api_key, self.get_query_location())

    def __str__(self):
        return self.name + " (" + self.address + ")"


class Room(models.Model):
    name = models.CharField(max_length=50)
    unit = models.ForeignKey(Unit)
    description = models.TextField(max_length=1000, null=True)
    width = models.DecimalField(max_digits=5, decimal_places=3, null=True)
    height = models.DecimalField(max_digits=5, decimal_places=3, null=True)


class Appliance(models.Model):
    name = models.CharField(max_length=50)
    room = models.ForeignKey(Room)
    cost = models.DecimalField(max_digits=2, decimal_places=2, null=True)
    xcoord = models.IntegerField(max_length=5, null=True)
    ycoord = models.IntegerField(max_length=5, null=True)
    width = models.IntegerField(max_length=5, null=True)
    height = models.IntegerField(max_length=5, null=True)
    weight = models.DecimalField(max_digits=5, decimal_places=2, null=True)
    metric = models.BooleanField(default=False)


class Sensor(models.Model):
    name = models.CharField(max_length=50)
    room = models.ForeignKey(Room)
    active = models.BooleanField(default=False)
    xcoord = models.IntegerField(max_length=5, null=True)
    ycoord = models.IntegerField(max_length=5, null=True)


class Light(Appliance):
    on = models.BooleanField(default=False)
    bulb = models.CharField(max_length=50, null=True)


class Thermostat(Appliance):
    temperature = models.DecimalField(max_digits=3, decimal_places=2, default=70.0)

webapp/views.py
from django.views.generic import ListView, FormView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import forms
from django.contrib.auth.views import logout_then_login
from django.contrib import auth


from models import Property, Unit
from mixins import LoginRequiredMixin


class IndexView(LoginRequiredMixin, ListView):
    template_name = 'webapp/index.html'
    context_object_name = 'properties'
    model = Property

    def get_queryset(self):
        return Property.objects.filter(owner=self.request.user)


class PropertyView(LoginRequiredMixin, ListView):
    template_name = 'webapp/property.html'
    context_object_name = 'units'
    model = Unit

    def get_queryset(self):
        return Unit.objects.filter(property=self.kwargs['id'])


class StatusView(ListView):
    template_name = 'webapp/index.html'
    context_object_name = 'units'
    model = Unit


def logout(request):
    return logout_then_login(request)


class LoginView(FormView):
    template_name = 'webapp/login.html'
    success_url = reverse_lazy('webapp:index')
    form_class = forms.AuthenticationForm

    def form_valid(self, form):
        result = super(LoginView, self).form_valid(form)
        auth.login(self.request, form.get_user())
        return result

webapp/templates/webapp/base.html
{% extends 'base.html' %}

{% block navbar-items-left-links %}
    {% include 'webapp/includes/navbar-items-links.html' %}
{% endblock %}

{% block navbar-responsive-links %}
    {% include 'webapp/includes/navbar-items-links.html' %}
{% endblock %}

webapp/templates/webapp/includes/navbar-items-links.html
<li><a href="">House Status</a></li>
<li><a href="">Lights</a></li>
<li><a href="">Climate</a></li>
<li><a href="">Music</a></li>
<li><a href="">Utilities Statistics</a></li>

webapp/templates/webapp/index.html
{% extends 'webapp/base.html' %}
{% block content %}
    <ul class="uk-tab" data-uk-tab="{connect:'#properties-tabs'}">
        <li><a href="">Properties</a></li>
        <li><a href="">Extra</a></li>
    </ul>

    <ul id="properties-tabs" class="uk-switcher uk-margin">
        <li>
            <table class="uk-table uk-table-hover">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Manager</th>
                    <th>Address</th>
                    <th class="uk-hidden-small">Description</th>
                    <th class="uk-hidden-small">Picture</th>
                </tr>
                </thead>
                <tbody>
                {% for property in properties %}
                    <tr class="clickable-row" href="{% url 'webapp:property' property.id %}">
                        <td>{{ property.name }}</td>
                        <td>{{ property.manager.username }}</td>
                        <td>{{ property.address }}, {{ property.zip_code }}</td>
                        <td class="uk-hidden-small">{{ property.description }}</td>
                        <td class="uk-hidden-small"><img src="{{ unit.get_street_view }}"/></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <script>jQuery(document).ready(function ($) {
                $(".clickable-row").click(function () {
                    window.document.location = $(this).attr("href");
                });
            });</script>
        </li>
    </ul>
{% endblock %}

webapp/templates/webapp/login.html
{% extends 'webapp/base.html' %}

{% block content %}
    {% include 'includes/form.html' with legend='Login' submit_text='Login' %}
{% endblock %}

webapp/templates/webapp/property.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}

webapp/templates/webapp/status.html
{% extends 'base.html' %}

{% block content %}
    <iframe
            width="600"
            height="450"
            frameborder="0" style="border:0"
            src="{{ home.get_map }}">
    </iframe>
{% endblock %}